#!/bin/sh
#
# This is use to run the various tests on various versions of Limpet

set -eu
usage='echo "usage: $0" 1>&2; exit 1'

while getopts "" OPT "$@"; do
    case "$OPT" in
    *)
        eval $usage
        ;;
    esac
done

shift $((OPTIND - 1))

if [ $# -ne 0 ]; then
    eval $usage
fi

# To run a specific test for all versions, set this to the test or tests
# to run. For example:
#   TESTS="simple"
# If this is blank, all tests will be run
TESTS=${TESTS:-}
echo "TESTS $TESTS"

# Set this to the versions of Limpet to run
VERSIONS=${VERSIONS:-"LINUX SINGLE_THREADED_LINUX"}
echo "VERSIONS $VERSIONS"

if [ -z "$TESTS" ]; then
    TEST_VAR=
else
    TEST_VAR="TESTS=\"$TESTS\""
fi

sep=""
errors=0

for version in $VERSIONS; do
    label="Running tests for version $version"
    printf "$sep"
    echo "$version"
    echo "$version" | sed -e 's/./=/g'
    set +e
    make VERSION=$version clean
    make VERSION=$version $TEST_VAR
    status=$?
    set -e

    if [ $status -ne 0 ]; then
        errors=$((errors + 1))
    fi

    sep="\n"
done

if [ $errors -eq 0 ]; then
    echo "There were no errors detected for any tests of versions configured"
    exit 0
else
    echo "There were $errors errors"
    exit 1
fi
